import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

const picsum = (seed: string, w: number, h: number) => `https://picsum.photos/seed/${seed}/${w}/${h}`;
const avatar = (index: number) => {
  const gender = index % 2 === 0 ? 'men' : 'women';
  const id = (index % 50) + 1;
  return `https://randomuser.me/api/portraits/${gender}/${id}.jpg`;
};

// Map old business category slugs to the new professional-business category slugs
// so demo professional profiles appear in the LinkedIn-style /businesses directory.
const CATEGORY_MAP: Record<string, string> = {
  'medical-services': 'healthcare-consulting',
  'healthcare-consulting': 'healthcare-consulting',
  'legal-services': 'legal-consulting',
  'technical-services': 'information-technology',
  'engineering-services': 'engineering-technical',
  'creative-services': 'design-creativity',
  'educational-services': 'training-development',
  'financial-services': 'accounting-finance',
  'agricultural-services': 'training-development',
  'logistic-services': 'management-consulting',
  'craft-services': 'project-management',
};

const SUBCATEGORY_MAP: Record<string, string> = {
  'general-clinics': 'medical-consultations',
  'home-medical-services': 'medical-consultations',
  'legal-consultations': 'general-legal-consulting',
  'notarization-contracts': 'contracts-notarization',
  'software-development': 'web-development',
  'technical-support': 'networks-cloud',
  'network-cybersecurity': 'cybersecurity',
  'architectural-design': 'architectural-design-prof',
  'engineering-supervision': 'engineering-supervision-prof',
  'photography': 'photography-prof',
  'graphic-design': 'graphic-design-prof',
  'video-production': 'video-production-prof',
  'content-writing': 'content-writing-prof',
  'vocational-training': 'vocational-training-prof',
  'accounting': 'general-accounting',
  'financial-consulting': 'financial-analysis',
  'tax-services': 'tax-consulting',
  'agricultural-consulting': 'personal-coaching',
  'delivery': 'process-improvement',
  'transportation': 'strategic-planning',
  'storage': 'process-improvement',
  'electrical-works': 'tech-project-management',
  'plumbing': 'construction-project-management',
  'carpentry': 'tech-project-management',
  'general-maintenance': 'construction-project-management',
};

const professionalProfiles = [
  {
    name: 'د. أحمد الخالدي',
    title: 'استشاري طب وجراحة الفم',
    categorySlug: 'medical-services',
    subcategorySlug: 'general-clinics',
    bio: 'استشاري طب وجراحة الفم والأسنان بخبرة تزيد عن 13 عاماً، متخصص في زراعة الأسنان وتجميل الابتسامة بأحدث التقنيات العالمية.',
    city: 'الرياض',
    phone: '0501112222',
    whatsapp: '966501112222',
    email: 'ahmad.khalidi@demo.gateo.com',
    experienceYears: 13,
    degree: 'بكالوريوس طب وجراحة الفم',
    academicSpecialization: 'جراحة الفم والفكين',
    certifications: 'شهادة زراعة الأسنان من أمريكا، عضو الجمعية السعودية لطب الأسنان',
    skills: ['زراعة الأسنان', 'تجميل الأسنان', 'تقويم الأسنان', 'علاج العصب'],
    languages: ['العربية', 'الإنجليزية'],
    services: [
      { name: 'تبييض الأسنان', description: 'جلسة تبييض احترافية بنتائج فورية', startingPrice: 699, duration: '60 دقيقة' },
      { name: 'زراعة الأسنان', description: 'زراعة بمواد عالمية مع ضمان 10 سنوات', startingPrice: 3500, duration: '120 دقيقة' },
      { name: 'تقويم الأسنان الشفاف', description: 'تقويم invisible يناسب العمل والمناسبات', startingPrice: 8500, duration: '30 دقيقة' },
    ],
    portfolioProjects: [
      { title: 'قبل وبعد تبييض الأسنان', description: 'نتائج جلسة تبييض واحدة', images: [picsum('dental-1', 800, 600)], videos: [], files: [] },
      { title: 'حالة زراعة أسنان كاملة', description: 'زراعة فورية للفك العلوي', images: [picsum('dental-2', 800, 600)], videos: [], files: [] },
    ],
  },
  {
    name: 'د. سارة العتيبي',
    title: 'استشارية الأمراض الجلدية',
    categorySlug: 'medical-services',
    subcategorySlug: 'home-medical-services',
    bio: 'استشارية جلدية وتجميلية، خبيرة في علاج مشاكل البشرة المختلفة وإزالة الشعر بالليزر والتقشير الطبي.',
    city: 'جدة',
    phone: '0502223333',
    whatsapp: '966502223333',
    email: 'sara.otaibi@demo.gateo.com',
    experienceYears: 8,
    degree: 'بكالوريوس الطب والجراحة',
    academicSpecialization: 'الأمراض الجلدية والتناسلية',
    certifications: 'زمالة الجلدية من كندا',
    skills: ['إزالة الشعر بالليزر', 'حقن الفيلر', 'البوتوكس', 'علاج حب الشباب'],
    languages: ['العربية', 'الإنجليزية'],
    services: [
      { name: 'إزالة الشعر بالليزر', description: 'جلسة لمنطقة واحدة بجهاز FDA معتمد', startingPrice: 450, duration: '45 دقيقة' },
      { name: 'تقشير كيميائي', description: 'تقشير طبي للبشرة الدهنية والمسام الواسعة', startingPrice: 550, duration: '40 دقيقة' },
      { name: 'حقن البلازما', description: 'علاج تساقط الشعر وتجديد البشرة', startingPrice: 900, duration: '60 دقيقة' },
    ],
    portfolioProjects: [
      { title: 'نتائج إزالة الشعر', description: 'بعد 6 جلسات ليزر', images: [picsum('derma-1', 800, 600)], videos: [], files: [] },
    ],
  },
  {
    name: 'فهد القحطاني',
    title: 'محامٍ واستشاري قانوني',
    categorySlug: 'legal-services',
    subcategorySlug: 'legal-consultations',
    bio: 'محامٍ مرخص بخبرة 13 عاماً في القضايا المدنية والتجارية والشركات، سابقاً قاضٍ مساعد في وزارة العدل.',
    city: 'الرياض',
    phone: '0503334444',
    whatsapp: '966503334444',
    email: 'fahd.qahtani@demo.gateo.com',
    experienceYears: 13,
    degree: 'بكالوريوس الشريعة والقانون',
    academicSpecialization: 'القانون التجاري',
    certifications: 'ترخيص مزاولة المحاماة، عضو لجنة التحكيم التجاري',
    skills: ['العقود التجارية', 'القضايا المدنية', 'التحكيم', 'صياغة العقود'],
    languages: ['العربية', 'الإنجليزية'],
    services: [
      { name: 'استشارة قانونية', description: 'استشارة مدتها ساعة مع دراسة مستندات', startingPrice: 500, duration: '60 دقيقة' },
      { name: 'صياغة عقد', description: 'عقد تجاري أو عقاري مخصص مع مراجعة قانونية', startingPrice: 1200, duration: 'يومان' },
      { name: 'تمثيل قضائي', description: 'متابعة قضية واحدة في المحكمة المختصة', startingPrice: 5000, duration: 'حسب القضية' },
    ],
    portfolioProjects: [
      { title: 'عقد تأسيس شركة', description: 'صياغة عقد تأسيس لشركة تقنية', images: [picsum('legal-1', 800, 600)], videos: [], files: [] },
    ],
  },
  {
    name: 'نورة الشمري',
    title: 'كاتبة عدل وخبيرة توثيق',
    categorySlug: 'legal-services',
    subcategorySlug: 'notarization-contracts',
    bio: 'كاتبة عدل معتمدة بخبرة 6 سنوات في توثيق العقود والوكالات والإقرارات للأفراد والشركات.',
    city: 'الدمام',
    phone: '0504445555',
    whatsapp: '966504445555',
    email: 'nora.shammari@demo.gateo.com',
    experienceYears: 6,
    degree: 'بكالوريوس القانون',
    academicSpecialization: 'القانون العام',
    certifications: 'ترخيص كتابة عدل',
    skills: ['توثيق العقود', 'الوكالات', 'الإقرارات', 'الاتفاقيات التجارية'],
    languages: ['العربية'],
    services: [
      { name: 'توثيق عقد عمل', description: 'إعداد ومراجعة عقود العمل وفق أنظمة العمل', startingPrice: 350, duration: '30 دقيقة' },
      { name: 'إعداد اتفاقية سرية', description: 'NDA مخصص لحماية الأعمال والبيانات', startingPrice: 600, duration: '60 دقيقة' },
      { name: 'توثيق وكالة', description: 'وكالة عامة أو خاصة مع التوجيه للكتابة', startingPrice: 250, duration: '30 دقيقة' },
    ],
    portfolioProjects: [],
  },
  {
    name: 'عبدالله العنزي',
    title: 'مهندس برمجيات رئيسي',
    categorySlug: 'technical-services',
    subcategorySlug: 'software-development',
    bio: 'مهندس برمجيات بخبرة 10 سنوات في بناء التطبيقات والمواقع الإلكترونية وحلول الأعمال الرقمية.',
    city: 'الرياض',
    phone: '0505556666',
    whatsapp: '966505556666',
    email: 'abdullah.anzi@demo.gateo.com',
    experienceYears: 10,
    degree: 'بكالوريوس علوم الحاسب',
    academicSpecialization: 'هندسة البرمجيات',
    certifications: 'AWS Solutions Architect, Google Cloud Professional',
    skills: ['Next.js', 'React Native', 'Node.js', 'Python', 'AWS'],
    languages: ['العربية', 'الإنجليزية'],
    services: [
      { name: 'تطوير موقع إلكتروني', description: 'موقع متجاوب مع لوحة تحكم كاملة', startingPrice: 5000, duration: 'أسبوعان' },
      { name: 'تطوير تطبيق جوال', description: 'تطبيق iOS وAndroid بخاصية Flutter', startingPrice: 15000, duration: 'شهر' },
      { name: 'استشارة تقنية', description: 'دراسة الحلول التقنية وأفضل الممارسات', startingPrice: 800, duration: '60 دقيقة' },
    ],
    portfolioProjects: [
      { title: 'تطبيق توصيل طلبات', description: 'تطبيق كامل للعملاء والسائقين', images: [picsum('tech-1', 800, 600)], videos: [], files: [] },
      { title: 'منصة تعليمية', description: 'منصة دورات مع بث مباشر', images: [picsum('tech-2', 800, 600)], videos: [], files: [] },
    ],
  },
  {
    name: 'خالد السبيعي',
    title: 'خبير أمن سيبراني',
    categorySlug: 'technical-services',
    subcategorySlug: 'network-cybersecurity',
    bio: 'خبير أمن سيبراني معتمد، يقدم خدمات اختبار الاختراق والمراجعة الأمنية وحماية البنية التحتية للشركات.',
    city: 'جدة',
    phone: '0506667777',
    whatsapp: '966506667777',
    email: 'khalid.subaie@demo.gateo.com',
    experienceYears: 7,
    degree: 'بكالوريوس الأمن السيبراني',
    academicSpecialization: 'الأمن السيبراني',
    certifications: 'CISSP, CEH, OSCP',
    skills: ['اختبار الاختراق', 'المراجعة الأمنية', 'الاستجابة للحوادث', 'SIEM'],
    languages: ['العربية', 'الإنجليزية'],
    services: [
      { name: 'اختبار اختراق', description: 'فحص ثغرات المواقع والشبكات وتقرير مفصل', startingPrice: 4000, duration: 'أسبوع' },
      { name: 'تدريب موظفين أمني', description: 'ورشة توعية بالهندسة الاجتماعية والتهديدات', startingPrice: 2500, duration: '3 ساعات' },
      { name: 'مراجعة أمنية شاملة', description: 'تقييم شامل للسياسات والبنية التحتية', startingPrice: 6000, duration: 'أسبوعان' },
    ],
    portfolioProjects: [
      { title: 'تقرير اختبار اختراق', description: 'تقرير مفصل لأحد البنوك', images: [picsum('cyber-1', 800, 600)], videos: [], files: [] },
    ],
  },
  {
    name: 'م. سلطان الدوسري',
    title: 'مهندس معماري رئيسي',
    categorySlug: 'engineering-services',
    subcategorySlug: 'architectural-design',
    bio: 'مهندس معماري بخبرة 10 سنوات في تصميم الفلل والمشاريع التجارية بأسلوب عصري يجمع الجمال والوظيفة.',
    city: 'الرياض',
    phone: '0507778888',
    whatsapp: '966507778888',
    email: 'sultan.dosari@demo.gateo.com',
    experienceYears: 10,
    degree: 'بكالوريوس الهندسة المعمارية',
    academicSpecialization: 'التصميم المعماري',
    certifications: 'ترخيص مزاولة المهنة، عضوية الهيئة السعودية للمهندسين',
    skills: ['التصميم المعماري', 'التصميم الداخلي', 'الإشراف الهندسي', 'AutoCAD'],
    languages: ['العربية', 'الإنجليزية'],
    services: [
      { name: 'تصميم فيلا سكنية', description: 'مخططات معمارية وديكور داخلي كامل', startingPrice: 18000, duration: 'شهر' },
      { name: 'تصميم مكتب تجاري', description: 'تخطيط المساحات والإنارة والديكور', startingPrice: 12000, duration: '3 أسابيع' },
      { name: 'استشارة تصميم', description: 'زيارة موقع واقتراحات مبدئية', startingPrice: 1000, duration: '90 دقيقة' },
    ],
    portfolioProjects: [
      { title: 'فيلا سكنية حديثة', description: 'تصميم فيلا 500 متر', images: [picsum('arch-1', 800, 600)], videos: [], files: [] },
    ],
  },
  {
    name: 'م. ناصر الحربي',
    title: 'مهندس إشراف إنشائي',
    categorySlug: 'engineering-services',
    subcategorySlug: 'engineering-supervision',
    bio: 'مهندس إشراف إنشائي بخبرة 8 سنوات في متابعة المشاريع السكنية والتجارية لضمان الجودة والالتزام بالمخططات.',
    city: 'جدة',
    phone: '0508889999',
    whatsapp: '966508889999',
    email: 'nasser.harbi@demo.gateo.com',
    experienceYears: 8,
    degree: 'بكالوريوس الهندسة المدنية',
    academicSpecialization: 'الإنشاءات',
    certifications: 'عضو الهيئة السعودية للمهندسين',
    skills: ['الإشراف الهندسي', 'مراجعة المخططات', 'استلام المشاريع', 'إدارة المواقع'],
    languages: ['العربية'],
    services: [
      { name: 'إشراف شهري', description: 'زيارات دورية وتقارير إنجاز', startingPrice: 4000, duration: 'شهر' },
      { name: 'مراجعة مخططات', description: 'مراجعة هندسية للمخططات المعمارية والإنشائية', startingPrice: 2500, duration: 'أسبوع' },
      { name: 'استلام مشروع', description: 'فحص شامل قبل الاستلام النهائي', startingPrice: 3500, duration: 'أسبوع' },
    ],
    portfolioProjects: [],
  },
  {
    name: 'ياسر المالكي',
    title: 'مصور فوتوغرافي احترافي',
    categorySlug: 'creative-services',
    subcategorySlug: 'photography',
    bio: 'مصور فوتوغرافي بخبرة 7 سنوات في تصوير المناسبات والمنتجات والأزياء مع خدمات المونتاج والتعديل.',
    city: 'الرياض',
    phone: '0509990000',
    whatsapp: '966509990000',
    email: 'yasser.malki@demo.gateo.com',
    experienceYears: 7,
    degree: 'دبلوم فنون بصرية',
    academicSpecialization: 'التصوير الفوتوغرافي',
    certifications: 'شهادة Adobe Certified Expert',
    skills: ['تصوير المنتجات', 'تصوير المناسبات', 'تصوير الأزياء', 'المونتاج'],
    languages: ['العربية', 'الإنجليزية'],
    services: [
      { name: 'تصوير منتجات', description: '10 صور احترافية للمتاجر الإلكترونية', startingPrice: 1200, duration: '120 دقيقة' },
      { name: 'تصوير مناسبة', description: 'تغطية مصورة لمدة 4 ساعات', startingPrice: 2500, duration: '4 ساعات' },
      { name: 'جلسة تصوير شخصية', description: 'جلسة في الاستوديو مع المكياج', startingPrice: 900, duration: '90 دقيقة' },
    ],
    portfolioProjects: [
      { title: 'جلسة أزياء', description: 'إعلان لأحد الماركات المحلية', images: [picsum('photo-1', 800, 600)], videos: [], files: [] },
      { title: 'تصوير منتجات عطر', description: 'إعلان منتجات تجميل', images: [picsum('photo-2', 800, 600)], videos: [], files: [] },
    ],
  },
  {
    name: 'لمى الزهراني',
    title: 'مصممة هوية بصرية',
    categorySlug: 'creative-services',
    subcategorySlug: 'graphic-design',
    bio: 'مصممة جرافيك متخصصة في الهوية البصرية والتصميمات الإعلانية والسوشيال ميديا بأسلوب مميز واحترافي.',
    city: 'الدمام',
    phone: '0510001111',
    whatsapp: '966510001111',
    email: 'lama.zahrani@demo.gateo.com',
    experienceYears: 6,
    degree: 'بكالوريوس التصميم الجرافيكي',
    academicSpecialization: 'التصميم الجرافيكي',
    certifications: 'Adobe Certified Professional',
    skills: ['الهوية البصرية', 'تصميم السوشيال ميديا', 'تصميم البروفايلات', 'Illustrator'],
    languages: ['العربية', 'الإنجليزية'],
    services: [
      { name: 'تصميم هوية بصرية', description: 'شعار + ألوان + خطوط + هوية كاملة', startingPrice: 3500, duration: 'أسبوع' },
      { name: 'تصميم سوشيال ميديا', description: '20 تصميم احترافي للمنصات', startingPrice: 900, duration: 'أسبوع' },
      { name: 'تصميم بروفايل شركة', description: 'بروفايل احترافي بصيغة PDF وطباعة', startingPrice: 1800, duration: 'أسبوعان' },
    ],
    portfolioProjects: [
      { title: 'هوية بصرية لعلامة تجارية', description: 'شعار وهوية كاملة', images: [picsum('design-1', 800, 600)], videos: [], files: [] },
    ],
  },
  {
    name: 'سعد العتيبي',
    title: 'فني كهربائي معتمد',
    categorySlug: 'craft-services',
    subcategorySlug: 'electrical-works',
    bio: 'فني كهربائي معتمد بخبرة 9 سنوات في تأسيس وصيانة التمديدات الكهربائية المنزلية والتجارية.',
    city: 'الرياض',
    phone: '0511112222',
    whatsapp: '966511112222',
    email: 'saad.otaibi@demo.gateo.com',
    experienceYears: 9,
    degree: 'دبلوم كهرباء صناعية',
    academicSpecialization: 'الكهرباء الصناعية',
    certifications: 'رخصة فني كهربائي من أمانة الرياض',
    skills: ['الصيانة الكهربائية', 'التأسيس الكهربائي', 'إنارة الديكور', 'اللوحات الكهربائية'],
    languages: ['العربية'],
    services: [
      { name: 'صيانة كهربائية', description: 'كشف وإصلاح أعطال المنزل', startingPrice: 200, duration: '60 دقيقة' },
      { name: 'تأسيس كهرباء', description: 'تمديدات كاملة للفلل والشقق', startingPrice: 2500, duration: 'حسب المساحة' },
      { name: 'تركيب إنارة ديكور', description: 'إنارة داخلية وخارجية بجودة عالية', startingPrice: 450, duration: '90 دقيقة' },
    ],
    portfolioProjects: [
      { title: 'تأسيس كهرباء فيلا', description: 'تمديدات كاملة لفيلا دورين', images: [picsum('elec-1', 800, 600)], videos: [], files: [] },
    ],
  },
  {
    name: 'بندر القحطاني',
    title: 'فني سباكة وصيانة',
    categorySlug: 'craft-services',
    subcategorySlug: 'plumbing',
    bio: 'فني سباكة بخبرة 8 سنوات في تأسيس وصيانة شبكات المياه والصرف، متخصص في كشف التسربات وتسليك المجاري.',
    city: 'جدة',
    phone: '0512223333',
    whatsapp: '966512223333',
    email: 'bander.qahtani@demo.gateo.com',
    experienceYears: 8,
    degree: 'دبلوم سباكة',
    academicSpecialization: 'السباكة',
    certifications: 'رخصة فني سباكة معتمد',
    skills: ['كشف التسربات', 'تسليك المجاري', 'تركيب الخلاطات', 'تأسيس شبكات المياه'],
    languages: ['العربية'],
    services: [
      { name: 'إصلاح تسرب', description: 'كشف وإصلاح تسربات المياه', startingPrice: 250, duration: '60 دقيقة' },
      { name: 'تسليك مجاري', description: 'تسليك بالضغط العالي مع ضمان', startingPrice: 300, duration: '60 دقيقة' },
      { name: 'تركيب خلاطات', description: 'تركيب أو تبديل خلاطات ومغاسل', startingPrice: 150, duration: '45 دقيقة' },
    ],
    portfolioProjects: [],
  },
  {
    name: 'منى الحربي',
    title: 'مدربة معتمدة في التطوير',
    categorySlug: 'educational-services',
    subcategorySlug: 'vocational-training',
    bio: 'مدربة معتمدة من صندوق تنمية الموارد البشرية، متخصصة في التسويق الرقمي والقيادة والمهارات الشخصية.',
    city: 'الرياض',
    phone: '0513334444',
    whatsapp: '966513334444',
    email: 'mona.harbi@demo.gateo.com',
    experienceYears: 7,
    degree: 'ماجستير إدارة الأعمال',
    academicSpecialization: 'التسويق والقيادة',
    certifications: 'CIPD, Google Digital Marketing',
    skills: ['التسويق الرقمي', 'القيادة', 'تطوير الذات', 'إدارة المشاريع'],
    languages: ['العربية', 'الإنجليزية'],
    services: [
      { name: 'دورة التسويق الرقمي', description: '12 ساعة تدريبية مع مشروع عملي', startingPrice: 1200, duration: '12 ساعة' },
      { name: 'دورة القيادة', description: 'مهارات القيادة وإدارة الفرق', startingPrice: 900, duration: '8 ساعات' },
      { name: 'تدريب خاص للشركات', description: 'برنامج مخصص للفريق مع تقرير أداء', startingPrice: 5000, duration: 'يوم كامل' },
    ],
    portfolioProjects: [
      { title: 'تدريب شركة تقنية', description: 'دورة قيادة لفريق من 30 موظف', images: [picsum('edu-1', 800, 600)], videos: [], files: [] },
    ],
  },
  {
    name: 'فهد المطيري',
    title: 'محاسب قانوني',
    categorySlug: 'financial-services',
    subcategorySlug: 'accounting',
    bio: 'محاسب قانوني بخبرة 8 سنوات في إعداد القوائم المالية والإقرارات الضريبية والزكاة للشركات الصغيرة والمتوسطة.',
    city: 'الرياض',
    phone: '0514445555',
    whatsapp: '966514445555',
    email: 'fahd.mutairi@demo.gateo.com',
    experienceYears: 8,
    degree: 'بكالوريوس المحاسبة',
    academicSpecialization: 'المحاسبة والزكاة',
    certifications: 'CPA, CMA',
    skills: ['القوائم المالية', 'الإقرار الضريبي', 'زكاة الشركات', 'التحليل المالي'],
    languages: ['العربية', 'الإنجليزية'],
    services: [
      { name: 'إعداد قوائم مالية', description: 'ميزانية + أرباح وخسائر + تدفقات نقدية', startingPrice: 2000, duration: 'أسبوع' },
      { name: 'إقرار ضريبي', description: 'إعداد ورفع الإقرار الضريبي والزكاة', startingPrice: 1200, duration: '3 أيام' },
      { name: 'استشارة مالية', description: 'تحليل مالي وخطة تكلفة للمشروع', startingPrice: 800, duration: '60 دقيقة' },
    ],
    portfolioProjects: [
      { title: 'مراجعة حسابات شركة', description: 'مراجعة سنوية لشركة تجارية', images: [picsum('fin-1', 800, 600)], videos: [], files: [] },
    ],
  },
  {
    name: 'عبدالرحمن الشهراني',
    title: 'مهندس زراعي واستشاري',
    categorySlug: 'agricultural-services',
    subcategorySlug: 'agricultural-consulting',
    bio: 'مهندس زراعي بخبرة 9 سنوات في تقديم استشارات زراعية متكاملة للمزارع والحدائق المنزلية.',
    city: 'أبها',
    phone: '0515556666',
    whatsapp: '966515556666',
    email: 'abdulrahman.shahrani@demo.gateo.com',
    experienceYears: 9,
    degree: 'بكالوريوس الهندسة الزراعية',
    academicSpecialization: 'الهندسة الزراعية',
    certifications: 'عضو الهيئة السعودية للمهندسين الزراعيين',
    skills: ['التسميد', 'أنظمة الري', 'مكافحة الآفات', 'إدارة المزارع'],
    languages: ['العربية'],
    services: [
      { name: 'زيارة مزرعة', description: 'فحص التربة والنباتات وخطة علاج', startingPrice: 600, duration: '120 دقيقة' },
      { name: 'تصميم نظام ري', description: 'تصميم شبكة ري حديثة للمزرعة', startingPrice: 2500, duration: 'أسبوع' },
      { name: 'استشارة هاتفية', description: 'استشارة زراعية مدتها 30 دقيقة', startingPrice: 200, duration: '30 دقيقة' },
    ],
    portfolioProjects: [
      { title: 'تصميم مزرعة استرالية', description: 'مزرعة صوب زراعية', images: [picsum('agri-1', 800, 600)], videos: [], files: [] },
    ],
  },
  {
    name: 'ماجد العلي',
    title: 'مدير عمليات لوجستية',
    categorySlug: 'logistic-services',
    subcategorySlug: 'delivery',
    bio: 'مدير عمليات لوجستية بخبرة 7 سنوات في إدارة خدمات التوصيل السريع للمتاجر والأفراد مع تتبع مباشر.',
    city: 'الرياض',
    phone: '0516667777',
    whatsapp: '966516667777',
    email: 'majed.ali@demo.gateo.com',
    experienceYears: 7,
    degree: 'بكالوريوس إدارة الأعمال',
    academicSpecialization: 'العمليات اللوجستية',
    certifications: 'CSCP, PMP',
    skills: ['إدارة التوصيل', 'التتبع المباشر', 'إدارة fleets', 'خدمة العملاء'],
    languages: ['العربية', 'الإنجليزية'],
    services: [
      { name: 'توصيل داخل المدينة', description: 'توصيل بنفس اليوم للأحياء الرئيسية', startingPrice: 35, duration: 'ساعتان' },
      { name: 'توصيل بين المدن', description: 'شحن للمدن الرئيسية خلال 24-48 ساعة', startingPrice: 80, duration: '1-2 يوم' },
      { name: 'خدمة توصيل للمتاجر', description: 'عقد شهري مع تتبع وتقارير', startingPrice: 3000, duration: 'شهر' },
    ],
    portfolioProjects: [
      { title: 'عقد توصيل لمتجر', description: 'تغطية شاملة لمدينة الرياض', images: [picsum('log-1', 800, 600)], videos: [], files: [] },
    ],
  },
];

async function main() {
  const demoPassword = await bcrypt.hash('demo123', 10);
  const country = await prisma.country.findFirst({ where: { code: 'SA' } });

  for (let i = 0; i < professionalProfiles.length; i++) {
    const prof = professionalProfiles[i];
    const mappedCategorySlug = CATEGORY_MAP[prof.categorySlug] || prof.categorySlug;
    const mappedSubcategorySlug = SUBCATEGORY_MAP[prof.subcategorySlug] || prof.subcategorySlug;

    const category = await prisma.category.findUnique({ where: { slug: mappedCategorySlug } });
    const subcategory = await prisma.subcategory.findUnique({ where: { slug: mappedSubcategorySlug } });

    if (!category || !subcategory) {
      console.warn('Skipping', prof.name, '- category/subcategory not found');
      continue;
    }

    const avatarUrl = avatar(i);
    const logoUrl = avatar(i); // personal logo = owner photo for demo

    const user = await prisma.user.upsert({
      where: { email: prof.email },
      update: {
        name: prof.name,
        avatar: avatarUrl,
        accountType: 'PROFESSIONAL',
      },
      create: {
        email: prof.email,
        name: prof.name,
        password: demoPassword,
        avatar: avatarUrl,
        role: 'USER',
        accountType: 'PROFESSIONAL',
        emailVerified: new Date(),
        updatedAt: new Date(),
      },
    });

    await prisma.professionalProfile.upsert({
      where: { userId: user.id },
      update: {
        title: prof.title,
        bio: prof.bio,
        personalLogo: logoUrl,
        categoryId: category.id,
        subcategoryId: subcategory.id,
        skills: prof.skills.join(', '),
        keywords: prof.skills.join(', '),
        degree: prof.degree,
        academicSpecialization: prof.academicSpecialization,
        experienceYears: prof.experienceYears,
        certifications: prof.certifications,
        services: JSON.stringify(prof.services) as any,
        countryId: country?.id || null,
        city: prof.city,
        languages: prof.languages.join(', '),
        phone: prof.phone,
        whatsapp: prof.whatsapp,
        email: prof.email,
        website: `https://${prof.email.split('@')[0]}.demo`,
        portfolioProjects: JSON.stringify(prof.portfolioProjects) as any,
        availableForWork: true,
        availableForFreelance: true,
        availableForConsultation: true,
        completedProjectsCount: Math.floor(Math.random() * 200) + 20,
        clientsCount: Math.floor(Math.random() * 150) + 10,
        status: 'ACTIVE',
        isVerified: true,
        isPublicOnGateway: true,
        updatedAt: new Date(),
      },
      create: {
        userId: user.id,
        title: prof.title,
        bio: prof.bio,
        personalLogo: logoUrl,
        categoryId: category.id,
        subcategoryId: subcategory.id,
        skills: prof.skills.join(', '),
        keywords: prof.skills.join(', '),
        degree: prof.degree,
        academicSpecialization: prof.academicSpecialization,
        experienceYears: prof.experienceYears,
        certifications: prof.certifications,
        services: JSON.stringify(prof.services) as any,
        countryId: country?.id || null,
        city: prof.city,
        languages: prof.languages.join(', '),
        phone: prof.phone,
        whatsapp: prof.whatsapp,
        email: prof.email,
        website: `https://${prof.email.split('@')[0]}.demo`,
        portfolioProjects: JSON.stringify(prof.portfolioProjects) as any,
        availableForWork: true,
        availableForFreelance: true,
        availableForConsultation: true,
        completedProjectsCount: Math.floor(Math.random() * 200) + 20,
        clientsCount: Math.floor(Math.random() * 150) + 10,
        status: 'ACTIVE',
        isVerified: true,
        isPublicOnGateway: true,
        updatedAt: new Date(),
      },
    });

    console.log('✅', prof.name);
  }

  console.log('✅ Professional profiles seeded successfully');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
